In [ ]:
import pandas as pd

cons = ["gplus","dblp"]

for a in cons:
    ofile = open("../"+a+"/subgraphs/edgeLabel.txt",'w')
    ifile = open("../"+a+"/edges.txt",'r')
    labels = pd.read_csv("../"+a+"/labels.txt", delimiter = ' ', header = None, index_col = 0)
    i = ifile.readline()
    while i:
        try:
            q = list(labels.loc[int(i.split()[0])][1])
            for j in q:
                ofile.write(i.split()[0]+' '+i.split()[1]+' '+str(int(j))+'\n')
        except:
            try:
                q = int(labels.loc[int(i.split()[0])][1])
                ofile.write(i.split()[0]+' '+i.split()[1]+' '+str(q)+'\n')
            except:
                pass
        i= ifile.readline()
    ofile.close()

In [7]:
labels.loc[int(i.split()[0])][1]

KeyError: 6962

In [6]:
a1 = 'twitter'
a2 = 'labels200'
labelFile = open('../'+a1+'/subgraphs/'+a2+'.txt', 'r')
labels = {}
line = labelFile.readline()
while line:
    try:
        labels[int(line.split()[1])] += 1
    except:
        labels[int(line.split()[1])] = 1
    line = labelFile.readline()

In [8]:
ls = pd.read_csv('../'+a1+'/subgraphs/'+a2+'.txt', delimiter= ' ', header = None)

In [16]:
ls.index = ls[0]

In [9]:
a3 = 'edges200'

In [24]:
edgeFile = open('../'+a1+'/subgraphs/'+a3+'.txt', 'r')

In [25]:
labels = {}

In [29]:
lines = edgeFile.readline()
j = 0
while lines:
    j += 1
    if j%1000 == 0:
        print (j, lines)
    try:
        a = list(ls[1][int(lines.split()[0])])
    except:
        a = [ls[1][int(lines.split()[0])]]
    for i in a:
        try:
            labels[i] += 1
        except:
            labels[i] = 1
    lines = edgeFile.readline()

(1000, '11661 1958663\n')
(2000, '1435362 2419028\n')
(3000, '11870 1291567\n')
(4000, '212856 21582\n')
(5000, '11952 409505\n')
(6000, '36487 892014\n')
(7000, '504380 177525\n')
(8000, '420953 18987\n')
(9000, '4523792 42224\n')
(10000, '12281 13554\n')
(11000, '412235 50728\n')
(12000, '12350 136859\n')
(13000, '265119 12408\n')
(14000, '1174913 5331\n')
(15000, '4254944 5707535\n')
(16000, '73181 911717\n')
(17000, '2113171 73181\n')
(18000, '12832 670035\n')
(19000, '101006 1311516\n')
(20000, '12965 140280\n')
(21000, '95133 669149\n')
(22000, '7111513 5935\n')
(23000, '6260 450333\n')
(24000, '2309 72369\n')
(25000, '39223 208566\n')
(26000, '199064 203619\n')
(27000, '13440 8061940\n')
(28000, '1282075 112458\n')
(29000, '13588 664779\n')
(30000, '128990 4570442\n')
(31000, '5935 7111513\n')
(32000, '13891 566160\n')
(33000, '13951 3308662\n')
(34000, '235781 494029\n')
(35000, '456121 6906\n')
(36000, '14156 150914\n')
(37000, '65192 531775\n')
(38000, '14252 1157790\n')
(39000, '199486 423701\n')
(40000, '509730 263396\n')
(41000, '1291768 133810\n')
(42000, '14627 128581\n')
(43000, '75862 435705\n')
(44000, '130017 1256399\n')
(45000, '311657 24450\n')
(46000, '621162 1255533\n')
(47000, '3428482 1131984\n')
(48000, '785303 116374\n')
(49000, '5368970 457457\n')
(50000, '15279 11720\n')
(51000, '130695 33376\n')
(52000, '15456 872922\n')
(53000, '730456 38496\n')
(54000, '927271 2617990\n')
(55000, '1174985 63369\n')
(56000, '12037391 66937\n')
(57000, '15833 1459335\n')
(58000, '56596 256530\n')
(59000, '571973 4162362\n')
(60000, '470778 1540968\n')
(61000, '131405 39794\n')
(62000, '131487 2130647\n')
(63000, '1010246 13177\n')
(64000, '2657209 6240\n')
(65000, '318068 3106\n')
(66000, '106960 42464\n')
(67000, '1785404 47796\n')
(68000, '131898 97559\n')
(69000, '1198992 47661\n')
(70000, '42445 538977\n')
(71000, '16968 12350\n')
(72000, '253793 236442\n')
(73000, '76842 127178\n')
(74000, '76846 1188726\n')
(75000, '289615 122904\n')
(76000, '9139157 5502708\n')
(77000, '244113 8984872\n')
(78000, '253929 13933500\n')
(79000, '5857836 530612\n')
(80000, '734266 2446955\n')
(81000, '4539884 3875\n')
(82000, '133031 33275\n')
(83000, '538733 460318\n')
(84000, '2814942 47796\n')
(85000, '133265 30388\n')
(86000, '10425876 866878\n')
(87000, '1107799 457457\n')
(88000, '476164 8482538\n')
(89000, '1188899 510140\n')
(90000, '627049 332069\n')
(91000, '87332 863\n')
(92000, '86375 200732\n')
(93000, '75261 754626\n')
(94000, '18987 4347939\n')
(95000, '2237311 47719\n')
(96000, '19231 42909\n')
(97000, '19247 485228\n')
(98000, '3370553 908005\n')
(99000, '5287 9971743\n')
(100000, '52888 134866\n')
(101000, '4030048 2454566\n')
(102000, '13510505 248357\n')
(103000, '134460 33741\n')
(104000, '104800 1697\n')
(105000, '1547789 6760477\n')
(106000, '134759 458423\n')
(107000, '134791 256157\n')
(108000, '934798 9424656\n')
(109000, '5337618 106216\n')
(110000, '1089579 45105\n')
(111000, '20348 1121948\n')
(112000, '583816 92975\n')
(113000, '325753 44752\n')
(114000, '36690 3031\n')
(115000, '36696 246846\n')
(116000, '958131 9123795\n')
(117000, '12505567 3025004\n')
(118000, '584694 15842\n')
(119000, '21004 19484\n')
(120000, '201961 1\n')
(121000, '586785 2857552\n')
(122000, '1750698 1912454\n')
(123000, '65409 236486\n')
(124000, '645821 872232\n')
(125000, '2610134 37129\n')
(126000, '21668 53229\n')
(127000, '432927 6397\n')
(128000, '957278 3862\n')
(129000, '1723347 9989\n')
(130000, '927679 136201\n')
(131000, '295092 1139633\n')
(132000, '75981 830305\n')
(133000, '22355 5467\n')
(134000, '326442 27951\n')
(135000, '1369811 39839\n')
(136000, '3057068 6397\n')
(137000, '315285 22834\n')
(138000, '137353 14627\n')
(139000, '1036478 5467\n')
(140000, '3889872 33962\n')
(141000, '5563677 5287\n')
(142000, '867807 19247\n')
(143000, '1247119 6620500\n')
(144000, '255192 256670\n')
(145000, '23350 28815\n')
(146000, '8871732 7891531\n')
(147000, '4075531 11861183\n')
(148000, '1098713 2537020\n')
(149000, '138130 160786\n')
(150000, '4886768 84539\n')
(151000, '11104716 1021221\n')
(152000, '7441848 1164971\n')
(153000, '3531415 3031\n')
(154000, '1648617 5467\n')
(155000, '479822 104376\n')
(156000, '835295 557276\n')
(157000, '630817 310876\n')
(158000, '1371852 395329\n')
(159000, '24450 128169\n')
(160000, '24450 427550\n')
(161000, '24460 830367\n')
(162000, '1602063 7489730\n')
(163000, '1642032 39794\n')
(164000, '3555829 1\n')
(165000, '6504771 243062\n')
(166000, '3561682 6397\n')
(167000, '179398 180711\n')
(168000, '445517 1140075\n')
(169000, '1036100 3031\n')
(170000, '9304254 6397\n')
(171000, '21071436 3031\n')
(172000, '661191 157490\n')
(173000, '21207751 1\n')
(174000, '2088442 2259221\n')
(175000, '961212 1709595\n')
(176000, '140024 254876\n')
(177000, '3586466 277675\n')
(178000, '4435483 1088398\n')
(179000, '4466402 769238\n')
(180000, '19543909 3031\n')
(181000, '327820 421115\n')
(182000, '405930 7166\n')
(183000, '2813660 21450474\n')
(184000, '3154203 133070\n')
(185000, '76020 198539\n')
(186000, '220361 4126281\n')
(187000, '407893 1602104\n')
(188000, '1037608 1249470\n')
(189000, '494799 24450\n')
(190000, '22413721 1\n')
(191000, '12688437 5467\n')
(192000, '26277 2511975\n')
(193000, '1374495 42550\n')
(194000, '9248921 39782\n')
(195000, '1061410 133102\n')
(196000, '777606 42224\n')
(197000, '6971829 1804136\n')
(198000, '9087489 5030343\n')
(199000, '12698451 3031\n')
(200000, '721894 6260\n')
(201000, '480520 25805\n')
(202000, '1206054 432424\n')
(203000, '1932588 243062\n')
(204000, '26900 5132137\n')
(205000, '7012185 11505732\n')
(206000, '27014 425937\n')
(207000, '7549384 1065\n')
(208000, '9043344 38496\n')
(209000, '2193091 76039\n')
(210000, '48700 1733889\n')
(211000, '11822941 3031\n')
(212000, '510673 2746139\n')
(213000, '2150833 47796\n')
(214000, '256578 15679\n')
(215000, '9128170 10070\n')
(216000, '704562 20942\n')
(217000, '525313 144634\n')
(218000, '1847974 88831\n')
(219000, '24411926 3031\n')
(220000, '606047 3452745\n')
(221000, '23796765 1\n')
(222000, '512985 2654671\n')
(223000, '3307378 8921696\n')
(224000, '1959732 36738\n')
(225000, '179923 180585\n')
(226000, '16422220 1\n')
(227000, '6045877 3031\n')
(228000, '16626980 89721\n')
(229000, '15797811 13911987\n')
(230000, '443702 953214\n')
(231000, '22316848 38496\n')
(232000, '9552513 1\n')
(233000, '5093113 1\n')
(234000, '634561 869160\n')
(235000, '329185 92975\n')
(236000, '144329 1905166\n')
(237000, '24783330 3031\n')
(238000, '10221644 13978269\n')
(239000, '11796705 571043\n')
(240000, '2601961 308870\n')
(241000, '340149 36659\n')
(242000, '1249594 24450\n')
(243000, '7371838 10039993\n')
(244000, '769038 482819\n')
(245000, '65613 209799\n')
(246000, '28815 693073\n')
(247000, '2886450 7767905\n')
(248000, '26407950 3031\n')
(249000, '3975564 318790\n')
(250000, '26583384 3031\n')
(251000, '1972336 129542\n')
(252000, '481330 1290113\n')
(253000, '3732978 1\n')
(254000, '3735532 3031\n')
(255000, '85121 668770\n')
(256000, '3740329 3031\n')
(257000, '145882 17912\n')
(258000, '7775048 17469633\n')
(259000, '353888 134460\n')
(260000, '29315 442228\n')
(261000, '369128 13151001\n')
(262000, '1729490 478826\n')
(263000, '6115263 1\n')
(264000, '6118505 38496\n')
(265000, '390768 429356\n')
(266000, '542853 97559\n')
(267000, '24254312 38496\n')
(268000, '3976460 4598433\n')
(269000, '898223 1\n')
(270000, '12112100 10365137\n')
(271000, '2475279 293255\n')
(272000, '29676 61675\n')
(273000, '1520178 4977060\n')
(274000, '186433 192369\n')
(275000, '559208 5634432\n')
(276000, '668265 309299\n')
(277000, '147464 326760\n')
(278000, '6214647 28956007\n')
(279000, '23417667 38496\n')
(280000, '404022 8116045\n')
(281000, '147733 31014\n')
(282000, '12403243 14379389\n')
(283000, '7773344 39794\n')
(284000, '13448034 12760874\n')
(285000, '29111177 3031\n')
(286000, '148170 12281\n')
(287000, '14001571 239091\n')
(288000, '481995 479899\n')
(289000, '636423 71211\n')
(290000, '6145042 47796\n')
(291000, '2860530 412748\n')
(292000, '25171171 243062\n')
(293000, '1055266 470834\n')
(294000, '28805851 38496\n')
(295000, '30022607 39794\n')
(296000, '2800235 96110\n')
(297000, '6146882 38496\n')
(298000, '6756409 13217396\n')

(299000, '30558 1248694\n')
(300000, '1242923 77059\n')
(301000, '42909 318712\n')
(302000, '12790919 3031\n')
(303000, '647093 305347\n')
(304000, '149606 481330\n')
(305000, '30768 139940\n')
(306000, '318182 218012\n')
(307000, '2852348 53339\n')
(308000, '30887 155364\n')
(309000, '5707900 6362114\n')
(310000, '522613 7382777\n')
(311000, '27378740 39794\n')
(312000, '2366425 619103\n')
(313000, '1196238 633791\n')
(314000, '8396228 353189\n')
(315000, '794205 6304074\n')
(316000, '9599781 38496\n')
(317000, '31221 1078302\n')
(318000, '150694 178597\n')
(319000, '2160701 1754285\n')
(320000, '30269540 3031\n')
(321000, '150914 148170\n')
(322000, '302468 11870\n')
(323000, '31703187 349106\n')
(324000, '31957546 3031\n')
(325000, '331475 139070\n')
(326000, '2987701 2452319\n')
(327000, '16673856 694917\n')
(328000, '24052774 3031\n')
(329000, '32195315 38496\n')
(330000, '2926672 5467\n')
(331000, '151683 159532\n')
(332000, '6793863 238343\n')
(333000, '151884 4630631\n')
(334000, '839015 309143\n')
(335000, '544232 6840379\n')
(336000, '4273555 527637\n')
(337000, '647322 3089\n')
(338000, '882227 19247\n')
(339000, '1911829 6638309\n')
(340000, '331866 544745\n')
(341000, '7974874 66937\n')
(342000, '70199 2868563\n')
(343000, '152709 19247\n')
(344000, '33230314 38496\n')
(345000, '4508376 303854\n')
(346000, '268720 133070\n')
(347000, '544547 31014\n')
(348000, '3457758 10713618\n')
(349000, '17271101 5797557\n')
(350000, '33495858 3031\n')
(351000, '284321 11382374\n')
(352000, '33630024 39794\n')
(353000, '11591506 16530891\n')
(354000, '1068169 5819521\n')
(355000, '32048 22455\n')
(356000, '28175694 3031\n')
(357000, '5800860 124810\n')
(358000, '32091 127178\n')
(359000, '710826 70199\n')
(360000, '34309956 38496\n')
(361000, '1513593 99216\n')
(362000, '871966 130652\n')
(363000, '3015858 90439\n')
(364000, '769620 39223\n')
(365000, '10809127 20229730\n')
(366000, '1092524 30558\n')
(367000, '2009473 2256394\n')
(368000, '14160250 38496\n')
(369000, '9137590 39794\n')
(370000, '1478356 6495904\n')
(371000, '17619407 3031\n')
(372000, '35034995 38496\n')
(373000, '155251 2728296\n')
(374000, '34519743 39794\n')
(375000, '155364 1204013\n')
(376000, '34481801 39782\n')
(377000, '1301035 180104\n')
(378000, '16599372 10070\n')
(379000, '5613292 5551654\n')
(380000, '1219225 1700115\n')
(381000, '20191879 39794\n')
(382000, '484446 166972\n')
(383000, '27861505 38496\n')
(384000, '36975327 39794\n')
(385000, '156014 150702\n')
(386000, '28878799 39794\n')
(387000, '608557 6305697\n')
(388000, '156208 97559\n')
(389000, '556172 4094555\n')
(390000, '21850751 12676111\n')
(391000, '38192680 38496\n')
(392000, '24952761 3031\n')
(393000, '8915922 1883938\n')
(394000, '9622310 39794\n')
(395000, '32608 101139\n')
(396000, '18143534 38496\n')
(397000, '545961 303475\n')
(398000, '1062824 28815\n')
(399000, '546115 741068\n')
(400000, '484927 22882\n')
(401000, '56820 9727304\n')
(402000, '1524139 2627040\n')
(403000, '21326974 19978528\n')
(404000, '21028856 887608\n')
(405000, '4407403 39794\n')
(406000, '19626808 66937\n')
(407000, '2932045 407564\n')
(408000, '485128 65760\n')
(409000, '9138035 22432637\n')
(410000, '429883 617736\n')
(411000, '599918 331866\n')
(412000, '7751076 3031\n')
(413000, '157698 308189\n')
(414000, '4082697 22398509\n')
(415000, '157783 75862\n')
(416000, '38027597 3031\n')
(417000, '40557691 3031\n')
(418000, '7520604 14659605\n')
(419000, '30778868 39794\n')
(420000, '158006 217934\n')
(421000, '21936843 66937\n')
(422000, '22061691 53663\n')
(423000, '39235073 39794\n')
(424000, '158206 4614910\n')
(425000, '1958749 39794\n')
(426000, '21640710 21640709\n')
(427000, '41631035 38496\n')
(428000, '9899655 3800003\n')
(429000, '6628718 34544\n')
(430000, '15084344 3147480\n')
(431000, '14964582 42182795\n')
(432000, '8477965 20896662\n')
(433000, '3417 446460\n')
(434000, '41035162 39782\n')
(435000, '596528 305018\n')
(436000, '218025 482911\n')
(437000, '4213669 1517613\n')
(438000, '1045004 43933034\n')
(439000, '43762694 66937\n')
(440000, '19976675 39782\n')
(441000, '158943 160643\n')
(442000, '1055013 2986639\n')
(443000, '42720518 38496\n')
(444000, '907929 692618\n')
(445000, '21581561 39782\n')
(446000, '44245169 39782\n')
(447000, '312851 2210124\n')
(448000, '44439998 3031\n')
(449000, '1815599 261353\n')
(450000, '1662422 4228193\n')
(451000, '42907662 3031\n')
(452000, '5323222 3031\n')
(453000, '1890453 20261012\n')
(454000, '43740941 15480989\n')
(455000, '496223 37959\n')
(456000, '43996178 38496\n')
(457000, '1566017 329249\n')
(458000, '774955 1301718\n')
(459000, '45857373 3031\n')
(460000, '334134 640834\n')
(461000, '306665 490354\n')
(462000, '9636299 38496\n')
(463000, '45078208 39794\n')
(464000, '460896 5872\n')
(465000, '13229550 39794\n')
(466000, '160010 496223\n')
(467000, '13471831 39782\n')
(468000, '19928085 400590\n')
(469000, '559701 7232017\n')
(470000, '47126997 38496\n')
(471000, '46447336 38496\n')
(472000, '10765708 1732836\n')
(473000, '13268350 67825\n')
(474000, '16533875 39839\n')
(475000, '547412 260309\n')
(476000, '421901 1036108\n')
(477000, '44740385 39794\n')
(478000, '3425103 14330522\n')
(479000, '11338259 19088838\n')
(480000, '160643 133599\n')
(481000, '2265734 24450\n')
(482000, '24988564 1065\n')
(483000, '5079597 3031\n')
(484000, '48029240 38496\n')
(485000, '421961 817571\n')
(486000, '3032594 2316105\n')
(487000, '12423800 39794\n')
(488000, '25514969 389666\n')
(489000, '3010980 104087\n')
(490000, '44033950 3031\n')
(491000, '45354747 39794\n')
(492000, '48386037 38496\n')
(493000, '923095 760650\n')
(494000, '4357419 22868612\n')
(495000, '2568947 48780668\n')
(496000, '8929031 22930943\n')
(497000, '2437390 5430335\n')
(498000, '1494651 4729758\n')
(499000, '25994995 39794\n')
(500000, '5502129 7238780\n')
(501000, '347192 905204\n')
(502000, '10272709 39794\n')
(503000, '49254822 39782\n')
(504000, '218589 5577642\n')
(505000, '15126433 79635\n')
(506000, '48169655 79635\n')
(507000, '786472 4682490\n')
(508000, '3771319 13453\n')
(509000, '486821 3011020\n')
(510000, '50769175 38496\n')
(511000, '40323144 38496\n')
(512000, '1697508 1038793\n')
(513000, '45307570 39782\n')
(514000, '20667191 79635\n')
(515000, '18794134 3336981\n')
(516000, '26056663 248810\n')
(517000, '51639482 79635\n')
(518000, '33165 133534\n')
(519000, '36796 840819\n')
(520000, '192022 36498\n')
(521000, '33275 13177\n')
(522000, '1 34564\n')
(523000, '5872 2898317\n')
(524000, '5667 45029\n')
(525000, '166972 185494\n')
(526000, '166976 11155\n')
(527000, '274577 2465408\n')
(528000, '33741 1293881\n')
(529000, '37413 65192\n')

In [22]:
ls[1][36295]

36295     3583
36295      530
36295     3091
36295      532
36295      848
36295    36336
Name: 1, dtype: int64

In [41]:
a = pd.DataFrame(labels,index = [0])

In [63]:
a = a.transpose().sort_values(by = 0, ascending = False).head(30)

In [54]:
b=list(a.index)

In [56]:
cons = ["100", "133", "150", "166", "175", "200"]
for i in cons:
    for inp2 in [30]:
        print((i, inp2))
        oFile = open('../twitter/subgraphs/labels'+i+'_'+str(inp2)+'.txt','w')
        iFile = open('../twitter/subgraphs/labels'+i+'.txt','r')
        line = iFile.readline()
        while line:
            if int(line.split()[1]) in b:
                oFile.write(line)
            line = iFile.readline()
        oFile.close()

('100', 30)
('133', 30)
('150', 30)
('166', 30)
('175', 30)
('200', 30)

In [122]:
float(9.99797)

9.99797

In [58]:
freqs =  [5,10,15,20,25,30]

In [61]:
for inp in ["200"]:
    for inp2 in freqs:
        print((inp, inp2))
        oFile = open('../twitter/subgraphs/labels'+inp+'_'+str(inp2)+'.txt','w')
        iFile = open('../twitter/subgraphs/labels'+inp+'.txt','r')
        line = iFile.readline()
        while line:
            if int(line.split()[1]) in b[:inp2]:
                oFile.write(line)
            line = iFile.readline()
        oFile.close()

('200', 5)
('200', 10)
('200', 15)
('200', 20)
('200', 25)
('200', 30)

In [119]:
def generate(ofile, querySize = -1, queryType = -1, bin_start = 0, bin_end = 20):
    ofile = ofile.head(bin_end).tail(bin_end-bin_start).reset_index(drop = True)
    if (querySize == -1):
        querySize = (np.random.randint(4)+1)*2
    if (queryType == -1):
        queryType = (np.random.randint(3)+2)
    st = []
    prev = -1
    bin_end = min(bin_end, len(ofile.index))
    
    if (queryType != 2):
        k = 2
    else:
        k = querySize
    for _ in range(querySize):
        j = np.random.choice(bin_end - bin_start, min(k,bin_end - bin_start), replace=False, p=ofile[1]/ofile[1].sum())
        if (queryType == 2):
            for l in j:
                st.append(ofile[0][l])
            break
        if ofile[0][j[0]] == prev:
            prev = ofile[0][j[1]]
        else:
            prev = ofile[0][j[0]]
        st.append(prev)
    st = list(st)
    if (queryType == 2):
        return('('+'U'.join(map(str,st))+')+')
    if (queryType == 4):
        return('(('+')+).(('.join(map(str,st))+')+)')
    if (queryType == 3):
        return('('+'.'.join(map(str,st))+')+')

In [120]:
nodes = pd.read_csv("../twitter/subgraphs/labels100.txt", delimiter = ' ', header=None)
for inp in ["200_15", "200_10", "200_5"]:
    input3 = ['mix']
    k = int(inp.split('_')[1])
    b = a.head(k)
    for inp2 in input3:
        oFile = open('../twitter/subgraphs/query'+str(inp)+'.txt','w')
        if inp2 == 'mix':
            inp2 = -1
        for i in range(10000):
            y = nodes[0][np.random.randint(len(nodes.index))]
            x = nodes[0][np.random.randint(len(nodes.index))]
            oFile.write('query ' + str(x) +' ' + str(y) + ' ' +generate(b, queryType=inp2)+"\n")
        oFile.close()

In [118]:
inp

'200_15'

In [100]:
ofile

           0             1
0        530  7.007310e-02
1       5962  6.535196e-02
2       3583  6.129050e-02
3        238  5.606654e-02
4       1406  4.545950e-02
5        242  4.467678e-02
6       1015  4.402654e-02
7       3091  4.365290e-02
8        191  4.297352e-02
9       5259  4.289246e-02
10       848  4.280026e-02
11      1314  3.965080e-02
12        70  3.906900e-02
13       532  3.886706e-02
14      3606  3.804608e-02
15      2911  3.648012e-02
16      5992  3.606786e-02
17      4501  3.555918e-02
18       740  3.437922e-02
19     38285  3.205908e-02
20       817  3.143496e-02
21      1326  3.131226e-02
22       610  3.110374e-02
23     39789  3.092712e-02
24      1330  3.002666e-02
25     41266  2.949388e-02
26      4075  2.937990e-02
27      8830  2.911716e-02
28      2786  2.860794e-02
29     38461  2.800828e-02
...      ...           ...
971   904149  1.055280e-03
972   668151  1.055080e-03
973    18792  1.055000e-03
974   501641  1.054980e-03
975    78700  1.054760e-03
976   341064  1.054660e-03
977   101275  1.054360e-03
978    67162  1.054220e-03
979   109279  1.053860e-03
980    20401  1.052460e-03
981    42534  1.051680e-03
982   100845  1.051560e-03
983   197001  1.047720e-03
984    53976  1.047160e-03
985   902092  1.047020e-03
986   904155  1.046640e-03
987     1060  1.046140e-03
988     9639  1.044800e-03
989    18718  1.042980e-03
990    53164  1.042580e-03
991      790  1.041520e-03
992    44578  1.040820e-03
993    12234  1.039000e-03
994      771  1.038620e-03
995    80582  1.036660e-03
996     4915  1.035440e-03
997    17981  1.032300e-03
998    15039  1.032300e-03
999    13728  1.031960e-03
1000      35  2.000000e-08

[1001 rows x 2 columns]

In [102]:
a

In [112]:
a

        0       1
0     191  133879
1     530  125670
2     767  115056
3     989  111228
4    5962  108924
5     238  108820
6   12352  108612
7     827  107839
8     772  104991
9   32741  104579
10  24450  104334
11   4969  103267
12   3215  101718
13  14153  101361
14   5064  101189
15   3583  100771
16    933  100625
17    784  100499
18    795  100494
19    796   99465
20    748   99464
21  11962   99358
22  16497   99067
23    242   99024
24   5259   98809
25    934   97524
26    782   97480
27   5286   97351
28   2845   97214
29    791   97135

In [123]:
pwd

u'/Users/sarisht/Desktop/ARRIVAL/ARRIVAL'

In [15]:
a = pd.read_csv("../dblp/querydb2.log", delimiter = ',')

In [16]:
b = pd.read_csv("../BBFS/dblpqdb2BBFS.txt", delimiter = ' ')

In [24]:
ds = ['gplus','dblp','freebase']
for d in ds:
    for e in [1,2,3,4,5]:
        a = pd.read_csv("../"+d+"/querydb"+str(e)+".log", delimiter = ',')
        b = pd.read_csv("../BBFS/"+d+"qdb"+str(e)+"BBFS.txt", delimiter = ' ')
        pospos = 0
        posbbfs = 0
        negbbfs = 0
        posrr = 0
        negrr = 0
        negneg = 0
        posneg = 0
        negpos = 0
        try:
            for i in range(10000):
                if b['Result'][i] == 1:
                    if a[' response'][i] == 1:
                        pospos+=1
                        posbbfs += b['Time'][i]
                        posrr += a[' time'][i]
                    else:
                        posneg += 1
                        posbbfs += b['Time'][i]
                        posrr += a[' time'][i]
                elif b['Result'][i] == 2:
                    if a[' response'][i] == 1:
                        pospos += 1
                        posbbfs += b['Time'][i]
                        posrr += a[' time'][i]
                    else:
                        negneg += 1
                        negbbfs += b['Time'][i]
                        negrr += a[' time'][i]
                else:
                    if a[' response'][i] == 1:
                        negpos+=1
                        negbbfs += b['Time'][i]
                        negrr += a[' time'][i]
                    else:
                        negneg += 1
                        negbbfs += b['Time'][i]
                        negrr += a[' time'][i]
        except:
            print(i)
        print(float(pospos)/(posneg+pospos), posbbfs/posrr, negbbfs/negrr)

8187
(0.9779891304347826, 3641.798150600016, 5075.227644943353)
(0.9903448275862069, 1013.8047556643371, 4.231499414143843)
(0.9782051282051282, 716.8518351146815, 603.0461648559934)
(0.9821428571428571, 352.9667294892698, 310.1947760929916)
(0.9853351955307262, 340.3687557724775, 228.36577321997729)
9135
(0.9541875447387258, 201.7920941700164, 342.4061393094004)
(0.9882075471698113, 413.3358049384865, 176.8183134411029)
(0.9904601571268238, 517.8902552592004, 172.95011750992427)
(0.9886947584789312, 451.81661947514317, 215.85677575491653)
(0.9812558575445174, 667.5685416252878, 97.64609766464439)

IOError: [Errno 2] File ../BBFS/freebaseqdb1BBFS.txt does not exist: '../BBFS/freebaseqdb1BBFS.txt'

In [18]:
pospos,negneg, posneg, negpos

(2095, 7880, 25, 0)

In [19]:
float(pospos)/(posneg+pospos)

0.9882075471698113

In [20]:
posbbfs

6033.430339159994

In [21]:
posbbfs/posrr

413.3358049384865

In [22]:
negbbfs/negrr

176.8183134411029

In [251]:
(posbbfs+negbbfs-6840)

39225.248705100006

In [248]:
(posbbfs-/(10000-negneg)

6.131141109814806

In [249]:
b.groupby('Result').count()

        Time
Result
0       5861
1       3455
2        684

In [252]:
b['Time'].max()

63.7199

In [254]:
60*684-6840

34200

In [4]:
line = "edge 195361 53256 2 1456980972\n"

In [5]:
intlist = map(int,line.split()[1:])

In [6]:
intlist[3]

1456980972

In [7]:

def generate(ofile, querySize = -1, queryType = -1, bin_start = 0, bin_end = 20):
    ofile = ofile.head(bin_end).tail(bin_end-bin_start).reset_index(drop = True)
    if (querySize == -1):
        querySize = (np.random.randint(4)+1)*2
    if (queryType == -1):
        queryType = (np.random.randint(3)+2)
    st = []
    prev = -1
    
    if (queryType != 2):
        k = 2
    else:
        k = querySize
    for _ in range(querySize):
        j = np.random.choice(bin_end - bin_start, min(k,bin_end - bin_start), replace=False, p=ofile[1]/ofile[1].sum())
        if (queryType == 2):
            for l in j:
                st.append(ofile[0][l])
            break
        if ofile[0][j[0]] == prev:
            prev = ofile[0][j[1]]
        else:
            prev = ofile[0][j[0]]
        st.append(prev)
    st = list(st)
    if (queryType == 2):
        return[('('+'U'.join(map(str,st))+')+'),st]
    if (queryType == 4):
        return[('(('+')+).(('.join(map(str,st))+')+)'),st]
    if (queryType == 3):
        return[('('+'.'.join(map(str,st))+')+'),st]

In [16]:
nodes = {"gplus":100000, "dblp":1750696, "freebase":3674915, "twitter":40000000}
input3 = ['mix',2,3,4]
for inp in ['gplus']:
    ofile = pd.read_csv('../'+inp+'/labelfrequency.txt',sep = " ", header = None).sort_values(by = 1, ascending = False).reset_index(drop = True)

    for inp2 in input3:
        oFile = open('../'+inp+'/query'+str(inp2)+'.txt','w')
        oFile2 = open('../'+inp+'/oldquery'+str(inp2)+'.txt','w')
        if inp2 == 'mix':
            inpx = -1
        else:
            inpx = 0
        for i in range(1000):
            if inpx == -1:
                inp2 = np.random.randint(3)+2
            qs = (np.random.randint(4)+1)*2
            y = np.random.randint(nodes[inp])
            x = np.random.randint(nodes[inp])
            k = generate(ofile, queryType=inp2, querySize=qs)
            oFile.write('query ' + str(x) +' ' + str(y) + ' ' + k[0] +"\n")
            oFile2.write('query ' + str(x) +' ' + str(y) + ' ' + str(inp2) +" " + str(qs) +" " +' '.join(map(str,k[1]))+ "\n")
        oFile.close()
        oFile2.close()

    for inp2 in input4:
        oFile = open('../'+inp+'/querydb'+str(inp2)+'.txt','w')
        oFile2 = open('../'+inp+'/oldquerydb'+str(inp2)+'.txt','w')
        for i in range(10000):
            qs = (np.random.randint(4)+1)*2
            inpx = np.random.randint(3)+2
            y = np.random.randint(nodes[inp])
            x = np.random.randint(nodes[inp])
            k = generate(ofile, queryType = inpx, querySize=qs, bin_start=(int(inp2)-1)*5, bin_end=int(inp2)*5)
            oFile.write('query ' + str(x) +' ' + str(y) + ' ' + k[0]+"\n")
            oFile2.write('query ' + str(x) +' ' + str(y) + ' ' + str(inpx) +" " + str(qs) +" " +' '.join(map(str,k[1]))+ "\n")
        oFile.close()

NameError: name 'input4' is not defined